services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-one
    user: root
    command: redpanda start
    ports:
      - "8092:8092"
      - "9092:9092"
      - "9093:9093"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info -X user=console-admin -X pass=password -X sasl.mechanism=SCRAM-SHA-256"] # TODO: add authentication (?)
      start_period: 2s
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./.volumes/redpanda/redpanda.yaml:/etc/redpanda/redpanda.yaml
      - ./.volumes/redpanda/data:/var/lib/redpanda/data

  # for adding cors to the pandaproxy
  nginx_pandaproxy:
    image: nginx:latest
    ports: 
      - 8091:8091
    volumes:
      - ./.nginx/nginx.pandaproxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      redpanda:
        condition: service_healthy

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      CONFIG_FILEPATH: /etc/redpanda/redpanda-console-config.yaml
    ports:
      - "8090:8080"
    volumes:
      - ./.volumes/console/redpanda-console-config.yaml:/etc/redpanda/redpanda-console-config.yaml
    depends_on:
      redpanda:
        condition: service_healthy